
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh scripts/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "always"
restartPolicyMaxRetries = 10
